dags:
  persistence:
    enabled: true
    existingClaim: centos-pv-claim
    accessMode: ReadOnlyMany
airflow:
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
    - username: user
      password: user123
      role: User
      email: user@example.com
      firstName: user
      lastName: user
